### ISSUE TITLE
Code to use this with Appium Python Client

### ISSUE THREAD

**Issue by Akulavenkatesh** [AppiumTestDistribution/appium-gestures-plugin#17]
Hi, can you please share some sample codes to use this plugin with Appium Python Client?
For Long Press or Vertical Swipe

**Comment by ShinjiruPP** [comment]
Hi! 

How to execute the swipes in Python using gesture plugin? Are there same examples? 

Thanks!

**Comment by mmonfared** [comment]
@Akulavenkatesh @ShinjiruPP 

I've recently published an article on Medium regarding this plugin (in Python).

https://monfared.medium.com/gestures-in-appium-part9-plugin-9f83b954a400

Also, created a PR to add in Documentation.
