### ISSUE TITLE
Plugin doesn't work when installed locally

### ISSUE THREAD

**Issue by zak-emobg** [AppiumTestDistribution/appium-gestures-plugin#2]
Hi,

I'm trying to implement a horizontal swipe gesture from right to left. The one currently implemented is from left to right.
But after installing the plugin locally I get the following error when trying to perform a gesture:

> [HTTP] 
> [HTTP] ?[37m-->?[39m ?[37mPOST?[39m ?[37m/wd/hub/session/0c116edc-8cbd-40ee-aa25-224c1cae6945/plugin/actions/dragAndDrop?[39m
> [HTTP] {"sourceId":"00000000-0000-004b-ffff-ffff0000005d","destinationId":"00000000-0000-004b-ffff-ffff00000040"}
> [Appium] Request to /wd/hub/session/0c116edc-8cbd-40ee-aa25-224c1cae6945/plugin/actions/dragAndDrop would normally be proxied, but plugin gestures (sessionless) wants to handle it internally. We'll avoid proxying in this case.
> [debug] [W3C (0c116edc)] Calling AppiumDriver.dragAndDrop() with args: ["00000000-0000-004b-ffff-ffff0000005d","00000000-0000-004b-ffff-ffff00000040","0c116edc-8cbd-40ee-aa25-224c1cae6945"]
> [Appium] Plugins which can handle cmd 'dragAndDrop': gestures (sessionless)
> [Appium] Plugin gestures (sessionless) is now handling cmd 'dragAndDrop'
> Source { height: 71, width: 64, x: 58, y: 1391 } Destination { height: 170, width: 1080, x: 0, y: 221 }
> [gestures] Performing Drag and Drop http://127.0.0.1:8200/wd/hub/session/51ee686a-154b-423e-99d6-10bf0b571bac/actions with {"actions":[{"id":"finger","type":"pointer","parameters":{"pointerType":"touch"},"actions":[{"duration":0,"x":90,"y":1426.5,"type":"pointerMove","origin":"viewport"},{"button":1,"type":"pointerDown"},{"duration":600,"type":"pause"},{"duration":600,"x":540,"y":306,"type":"pointerMove","origin":"viewport"},{"button":1,"type":"pointerUp"}]}]}
> [gestures] Drag and Drop for android
> [Appium] Command 'dragAndDrop' was not handled by the following beahviors or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["gestures (sessionless)"].
> [debug] [W3C (0c116edc)] Encountered internal error running command: Error: Request failed with status code 400
> [debug] [W3C (0c116edc)]     at createError (/Users/zakaria.boutami/Repos/QA/appium-gestures-plugin/node_modules/axios/lib/core/createError.js:16:15)
> [debug] [W3C (0c116edc)]     at settle (/Users/zakaria.boutami/Repos/QA/appium-gestures-plugin/node_modules/axios/lib/core/settle.js:17:12)
> [debug] [W3C (0c116edc)]     at IncomingMessage.handleStreamEnd (/Users/zakaria.boutami/Repos/QA/appium-gestures-plugin/node_modules/axios/lib/adapters/http.js:269:11)
> [debug] [W3C (0c116edc)]     at IncomingMessage.emit (node:events:402:35)
> [debug] [W3C (0c116edc)]     at endReadableNT (node:internal/streams/readable:1340:12)
> [debug] [W3C (0c116edc)]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> [HTTP] <-- POST /wd/hub/session/0c116edc-8cbd-40ee-aa25-224c1cae6945/plugin/actions/dragAndDrop 500 701 ms - 680
> [HTTP] 

This also happens when installing locally the original version of the plugin without any modification

**Comment by saikrishna321** [comment]
@zak-emobg This is fixed in the latest.
