### ISSUE TITLE
Install or update appium-gestures-plugin required for W3c Actions/Gestures implementation when using Appium 2.0

### ISSUE THREAD

**Issue by vnuta9** [AppiumTestDistribution/appium-gestures-plugin#74]
I am using Appium2.0.0-beta66 version. Since TouchAction class being used for the gesture/actions is being deprecated, I am supposed to install appium-gestures-plugin ([from](https://github.com/AppiumTestDistribution/appium-gestures-plugin) ) and use it.

When I try to run the command

`$appium plugin install --source=npm appium-gestures-plugin`
as was suggested, I am getting the message

✔ Installing 'appium-gestures-plugin'
Error: ✖ A plugin named "gestures" is already installed. Did you mean to update?
I tried to check the installed plugins

`$appium plugin list --installed`
✔ Listing installed plugins

- relaxed-caps@1.0.0-beta.13 [installed (npm)]
- images@1.3.7 [installed (npm)]
- execute-driver@2.0.6 [installed (npm)]
- gestures@1.0.0-beta.4 [installed (npm)]

Then ran this command:
`$appium plugin update  appium-gestures-plugin
`
I got back this message:
**Error: ✖ The plugin "appium-gestures-plugin" was not installed, so can't be updated**
**How to update the existing 'gestures@1.0.0-beta.4' to gestures@2.0.0 ?**

**Comment by jlipps** [comment]
The name of the plugin in the list is `gestures` so your command should be `appium plugin update gestures`

**Comment by vnuta9** [comment]
@jlipps 
Thanks for your helpful reply.
When I ran the command,
`$appium plugin update gestures`
I got the message: 
**_✔ Checking if plugin 'gestures' is updatable
✔ Checking if plugin 'gestures' needs an update
ℹ Update report:
✖   - 'gestures' failed to update: Error: ✖ The plugin 'gestures' has a major revision update (1.0.0-beta.4 => 2.0.0), which could include breaking changes._** If you want to apply this update, 

`re-run with --unsafe`

Is it OK to run that command ??

`appium plugin update gestures --unsafe`

I am assuming that it is only suggesting that it is updating to ver2.0, which is not backward compatible.

**Comment by jlipps** [comment]
That's right. There's no guarantee that v1 -> v2 is not going to have breaking changes, so appium asks you to rerun the command with `--unsafe`. The only way to know for sure if it's a good idea is to read the changelog for the plugin in question

**Comment by saikrishna321** [comment]
@vnuta9 As jlipps mentioned v2 has no backward backward compatible. Going forward from v2 we will maintain backward compatible. 

v1->v2 we moved into driver.execute()
