### ISSUE TITLE
Installing the appium-gesture-plugin does have any other side effects ?

### ISSUE THREAD

**Issue by vnuta9** [AppiumTestDistribution/appium-gestures-plugin#82]
I am running **appium ver 2.0.0-beta66 and java-client ver8.5,Node ver18.15.0 JDK 15** on Mac Ventura ver 13.3.1a.

I have a legacy gestures code using **TouchAction** classes which works sporadically on Android. iOS is little bit more consistent. I have culled together code for all the **swipe/scroll, tap, long press** methods using the W3cAction classes like **Sequence** etc.,.Also collected code for all the above methods using gesture plugin too.

Before jumping the gun by running the command
`appium plugin update gestures --unsafe`
 to install the gesture plugin, I am thinking about the features I may lose by installing the gestures plugin.
 

- Could I be able to run the code with legacy code with 'TouchAction' class, until it's support is fully removed  ?
- Can I use the code I collected for **swipe/scroll/tap** methods using W3cAction classes from org.openqa.selenium.interactions package ?

**Comment by saikrishna321** [comment]
Plugin has its own implementation and does not override any logic on gestures at server side. 

All the existing commands will work.
